import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from "next/font/google"
import "./globals.css";
import { CartContextProvider } from './context/CartContext';
import { Toaster } from "react-hot-toast";
import { auth } from "@/auth";
import Header from "./components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const pop = Poppins({ subsets: ["latin"], weight: '400' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const user = session?.user

  return (
    <html lang="en">
      <body
        className={`${pop.className} antialiased `}
      >
        <CartContextProvider>
          <Header user={user} />
          {children}
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
        </CartContextProvider>
      </body>
    </html>
  );
}
